version: '3.4'

services:
  apirestnodejs:
    image: apirestnodejs
    build:
      context: .
      dockerfile: ./Dockerfile
      env_file:
        .env 
    environment:
      NODE_ENV: production
      DB_HOST: db  # Nombre del servicio de PostgreSQL (si lo usas)
      DB_USER: postgres
      DB_PASSWORD: cristian
      DB_NAME: postgres
      DB_PORT: 5432
    ports:  
      - 4000:4000
    depends_on:
      - db
    restart: always  # Reinicia si falla

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cristian
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: 

