# Usa una imagen de Node.js
FROM node:18

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos del proyecto al contenedor
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la API
COPY . .

# Expone el puerto en el que corre la API (cambia si usas otro)
EXPOSE 4000

# Comando para iniciar la API
CMD ["npm", "start"]
