version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cristian
      POSTGRES_DB: postgres2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_node
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: miusuario
      DB_PASSWORD: mipassword
      DB_NAME: midatabase
      DB_PORT: 5432
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]  # Usa "start" si no usas nodemon

volumes:
  pgdata:
